using System.IO;
using Newtonsoft.Json.Linq;
using NUnit.Framework;
using UnityEngine;

namespace Lastseen.Tests
{
    /// <summary>
    /// Replays lastseen/packages/shared/test-vectors/geometry.json, generated by `pnpm vectors` from the TypeScript reference in
    /// packages/shared/src/geometry.ts. If a test here fails, the C# port drifted from the TypeScript (or the vectors are stale).
    /// </summary>
    public class LastseenGeoTests
    {
        const double Tol = 1e-6;
        static JObject vectors;

        [OneTimeSetUp]
        public void Load()
        {
            string path = Path.GetFullPath(Path.Combine(Application.dataPath, "..", "lastseen", "packages", "shared", "test-vectors", "geometry.json"));
            Assert.IsTrue(File.Exists(path), "missing " + path + " (run `pnpm vectors` in lastseen/)");
            vectors = JObject.Parse(File.ReadAllText(path));
        }

        static double D(JToken t) { return (double)t; }

        [Test]
        public void Wrap180AndWrap360()
        {
            foreach (var c in vectors["wrap180"]) Assert.AreEqual(D(c["out"]), Geo.Wrap180(D(c["in"])), Tol, "wrap180 " + c["in"]);
            foreach (var c in vectors["wrap360"]) Assert.AreEqual(D(c["out"]), Geo.Wrap360(D(c["in"])), Tol, "wrap360 " + c["in"]);
        }

        [Test]
        public void Azimuth()
        {
            foreach (var c in vectors["azimuth"]) Assert.AreEqual(D(c["out"]), Geo.AzimuthDeg(D(c["dx"]), D(c["dy"])), Tol, c.ToString());
        }

        [Test]
        public void ArrowAngleFromHeading()
        {
            foreach (var c in vectors["arrowFromHeading"])
            {
                var p = c["pose"];
                var t = c["target"];
                Assert.AreEqual(D(c["angle"]), Geo.ArrowAngleFromHeading(D(t["x"]), D(t["y"]), D(p["x"]), D(p["y"]), D(p["headingDeg"])), Tol, c.ToString());
            }
        }

        [Test]
        public void PdrStep()
        {
            foreach (var c in vectors["pdrStep"])
            {
                double nx, ny;
                Geo.PdrStep(D(c["from"]["x"]), D(c["from"]["y"]), D(c["headingDeg"]), D(c["stepLengthM"]), out nx, out ny);
                Assert.AreEqual(D(c["out"]["x"]), nx, Tol);
                Assert.AreEqual(D(c["out"]["y"]), ny, Tol);
            }
        }

        [Test]
        public void CalibrateHeadOffset()
        {
            foreach (var c in vectors["calibrateHeadOffset"]) Assert.AreEqual(D(c["out"]), Geo.CalibrateHeadOffset(D(c["chestHeadingDeg"]), D(c["headYawDeg"])), Tol);
        }

        [Test]
        public void HeadHeadingAndArrow()
        {
            foreach (var c in vectors["headHeading"])
            {
                long now = (long)c["now"];
                long headT = (long)c["headT"];
                Assert.AreEqual(D(c["headHeading"]), Geo.HeadHeading(D(c["chest"]), true, headT, D(c["headYaw"]), D(c["offset"]), now), Tol, (string)c["name"]);
                Assert.AreEqual(D(c["arrowToNorthEast"]), Geo.ArrowAngle(3, 3, 0, 0, D(c["chest"]), true, headT, D(c["headYaw"]), D(c["offset"]), now), Tol, (string)c["name"]);
            }
        }

        [Test]
        public void NoHeadPoseUsesTheChestHeading()
        {
            Assert.AreEqual(20, Geo.HeadHeading(20, false, 0, 100, 5, 1000), Tol);
        }

        [Test]
        public void SmoothAngle()
        {
            foreach (var c in vectors["smoothAngle"]) Assert.AreEqual(D(c["out"]), Geo.SmoothAngle(D(c["prevDeg"]), D(c["targetDeg"]), D(c["alpha"])), Tol);
        }

        [Test]
        public void ClipDistance()
        {
            foreach (var c in vectors["clipDistance"])
            {
                double? input = null;
                if (c["in"].Type == JTokenType.String) input = double.NaN; // the vectors write NaN as the string "NaN"
                else if (c["in"].Type != JTokenType.Null) input = D(c["in"]);
                Assert.AreEqual(D(c["out"]), Geo.ClipDistance(input), Tol, c.ToString());
            }
        }

        [Test]
        public void PoseConfidence()
        {
            foreach (var c in vectors["poseConfidence"]) Assert.AreEqual(D(c["out"]), Geo.PoseConfidence(D(c["steps"]), D(c["sec"])), Tol);
        }

        [Test]
        public void ChooseMode()
        {
            foreach (var c in vectors["chooseMode"]) Assert.AreEqual((string)c["out"], Geo.ChooseMode(D(c["confidence"]), D(c["distance"])), c.ToString());
        }

        [Test]
        public void ObjectPositionFromDepth()
        {
            foreach (var c in vectors["objectPositionFromDepth"])
            {
                var p = Geo.ObjectPositionFromDepth(D(c["pose"]["x"]), D(c["pose"]["y"]), D(c["headingDeg"]), D(c["u"]), D(c["v"]), D(c["depthM"]), D(c["hfovDeg"]), D(c["aspect"]));
                Assert.AreEqual(D(c["out"]["x"]), p.X, Tol, c.ToString());
                Assert.AreEqual(D(c["out"]["y"]), p.Y, Tol, c.ToString());
                Assert.AreEqual(D(c["out"]["zUp"]), p.ZUp, Tol, c.ToString());
                Assert.AreEqual(D(c["out"]["rangeM"]), p.RangeM, Tol, c.ToString());
            }
        }

        [Test]
        public void StepDetectorFindsTheSameStepsAsTheTypeScript()
        {
            var det = new StepDetector();
            var got = new System.Collections.Generic.List<long>();
            foreach (var s in vectors["stepDetector"]["samples"])
                if (det.Push(D(s[0]), D(s[1]), D(s[2]), D(s[3]))) got.Add((long)s[3]);
            var want = new System.Collections.Generic.List<long>();
            foreach (var t in vectors["stepDetector"]["stepTimesMs"]) want.Add((long)t);
            CollectionAssert.AreEqual(want, got);
            Assert.Greater(got.Count, 28);
        }

        [Test]
        public void YawOfForwardMatchesUnityRotations()
        {
            foreach (float yaw in new[] { 0f, 30f, 90f, 180f, 270f, 359f })
            {
                var q = Quaternion.Euler(0f, yaw, 0f);
                Assert.AreEqual(yaw, Geo.YawOfForward(q.x, q.y, q.z, q.w), 1e-3, "yaw " + yaw);
            }
            // pitch and roll do not change the azimuth of where the camera looks
            var tilted = Quaternion.Euler(20f, 90f, 0f);
            Assert.AreEqual(90, Geo.YawOfForward(tilted.x, tilted.y, tilted.z, tilted.w), 1e-3);
        }
    }
}
