// Cross-language test vectors. The TypeScript in packages/shared/src/geometry.ts is the reference implementation; the Unity
// C# port (Assets/Scripts/Lastseen) must produce the same numbers. This writes packages/shared/test-vectors/geometry.json, and
// scripts/vectors.test.ts fails when the file is stale. The Unity EditMode tests read the same file.
//   pnpm vectors
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  StepDetector,
  arrowAngle,
  arrowAngleFromHeading,
  azimuthDeg,
  calibrateHeadOffset,
  chooseMode,
  clipDistance,
  headHeading,
  objectPositionFromDepth,
  pdrStep,
  poseConfidence,
  smoothAngle,
  wrap180,
  wrap360,
} from "../packages/shared/src/geometry";

export const VECTORS_PATH = resolve(dirname(fileURLToPath(import.meta.url)), "..", "packages", "shared", "test-vectors", "geometry.json");

/** Round like the file will be read back: JSON numbers with at most 9 decimals. */
const r = (n: number) => Number(n.toFixed(9));

/** Deterministic pseudo-noise so the accelerometer stream is reproducible. */
function lcg(seed: number) {
  let s = seed >>> 0;
  return () => ((s = (Math.imul(s, 1664525) + 1013904223) >>> 0) / 4294967296 - 0.5);
}

/** 30 Hz accelerometer: 2 s still, 10 s walking at 1.8 steps/s, 4 s still, 8 s walking at 2.2 steps/s, 2 s still. */
function accelStream() {
  const noise = lcg(7);
  const samples: Array<[number, number, number, number]> = [];
  const hz = 30;
  for (let i = 0; i < 26 * hz; i++) {
    const t = i / hz;
    let amp = 0;
    let f = 0;
    if (t >= 2 && t < 12) [amp, f] = [3.2, 1.8];
    else if (t >= 16 && t < 24) [amp, f] = [3.6, 2.2];
    const g = 9.81 + amp * Math.sin(2 * Math.PI * f * t) + noise() * 0.1;
    // phone upright on the chest: gravity mostly along -y, a little on z
    samples.push([r(0.3 * noise()), r(-g * 0.98), r(g * 0.2), Math.round(t * 1000) + 1_000_000]);
  }
  return samples;
}

export function buildVectors() {
  const angles = [-725, -360, -270, -181, -180, -179.5, -90, -1e-9, 0, 45, 90, 179.5, 180, 181, 270, 359.9, 360, 725];
  const offsets: Array<[number, number]> = [[0, 1], [1, 0], [0, -1], [-1, 0], [1, 1], [-3, 4], [2.5, -0.5], [0, 0]];
  const poses: Array<{ x: number; y: number; headingDeg: number }> = [
    { x: 0, y: 0, headingDeg: 0 },
    { x: 1, y: 2, headingDeg: 90 },
    { x: -3, y: 0.5, headingDeg: 270 },
    { x: 0, y: 0, headingDeg: 359 },
  ];
  const targets = [{ x: 0, y: 5 }, { x: 4, y: 0 }, { x: -2, y: -2 }, { x: 1, y: 2 }];

  const arrowCases = poses.flatMap((pose) => targets.map((target) => ({ pose, target, angle: r(arrowAngleFromHeading(target, pose, pose.headingDeg)) })));

  const now = 1_800_000_000_000;
  const headCases = [
    { name: "fresh head pose overrides the chest heading", headYaw: 100, headT: now - 50, offset: 5, chest: 20 },
    { name: "stale head pose falls back to the chest heading", headYaw: 100, headT: now - 400, offset: 5, chest: 20 },
    { name: "future timestamp is treated as stale", headYaw: 100, headT: now + 10, offset: 0, chest: 20 },
    { name: "wraps past 360", headYaw: 350, headT: now - 10, offset: 30, chest: 0 },
  ].map((c) => {
    const pose = { headingDeg: c.chest, x: 0, y: 0 };
    const head = { t: c.headT, yawDeg: c.headYaw };
    return {
      ...c,
      now,
      headHeading: r(headHeading(pose, head, c.offset, now)),
      arrowToNorthEast: r(arrowAngle({ x: 3, y: 3 }, pose, head, c.offset, now)),
    };
  });

  const detector = new StepDetector();
  const stream = accelStream();
  const stepTimes: number[] = [];
  for (const [ax, ay, az, t] of stream) if (detector.push(ax, ay, az, t)) stepTimes.push(t);

  return {
    _about: "Generated by scripts/gen-vectors.ts from packages/shared/src/geometry.ts. Do not edit; run `pnpm vectors`.",
    wrap180: angles.map((a) => ({ in: a, out: r(wrap180(a)) })),
    wrap360: angles.map((a) => ({ in: a, out: r(wrap360(a)) })),
    azimuth: offsets.map(([dx, dy]) => ({ dx, dy, out: r(azimuthDeg(dx, dy)) })),
    arrowFromHeading: arrowCases,
    pdrStep: [
      { from: { x: 0, y: 0 }, headingDeg: 0, stepLengthM: 0.7 },
      { from: { x: 1, y: 1 }, headingDeg: 90, stepLengthM: 0.7 },
      { from: { x: -2, y: 3 }, headingDeg: 225, stepLengthM: 0.55 },
    ].map((c) => {
      const p = pdrStep(c.from, c.headingDeg, c.stepLengthM);
      return { ...c, out: { x: r(p.x), y: r(p.y) } };
    }),
    calibrateHeadOffset: [[90, 80], [10, 350], [350, 10], [0, 180]].map(([chest, yaw]) => ({ chestHeadingDeg: chest, headYawDeg: yaw, out: r(calibrateHeadOffset({ headingDeg: chest! }, { yawDeg: yaw! })) })),
    headHeading: headCases,
    smoothAngle: [[350, 10, 0.5], [10, 350, 0.25], [0, 90, 0.2], [170, -170, 0.5]].map(([prev, target, alpha]) => ({ prevDeg: prev, targetDeg: target, alpha, out: r(smoothAngle(prev!, target!, alpha!)) })),
    clipDistance: [null, undefined, Number.NaN, -1, 0, 0.1, 0.3, 1.5, 3, 9].map((d) => ({ in: d === undefined ? null : Number.isNaN(d) ? "NaN" : d, out: r(clipDistance(d)) })),
    poseConfidence: [[0, 0], [60, 0], [0, 300], [120, 600], [500, 4000]].map(([steps, sec]) => ({ steps, sec, out: r(poseConfidence(steps!, sec!)) })),
    chooseMode: [[0.9, 3], [0.2, 3], [0.9, 20], [0.35, 15], [0.349, 15]].map(([confidence, distance]) => ({ confidence, distance, out: chooseMode(confidence!, distance!) })),
    objectPositionFromDepth: [
      { pose: { x: 0, y: 0 }, headingDeg: 0, u: 0.5, v: 0.5, depthM: 2, hfovDeg: 70, aspect: 4 / 3 },
      { pose: { x: 1, y: 2 }, headingDeg: 90, u: 1, v: 0.5, depthM: 2, hfovDeg: 90, aspect: 4 / 3 },
      { pose: { x: -1, y: 0 }, headingDeg: 200, u: 0.2, v: 0.8, depthM: 3.3, hfovDeg: 65, aspect: 1.5 },
      { pose: { x: 0, y: 0 }, headingDeg: 45, u: 0.7, v: 0.575, depthM: 1.37, hfovDeg: 70, aspect: 4 / 3 },
    ].map((c) => {
      const p = objectPositionFromDepth(c.pose, c.headingDeg, c.u, c.v, c.depthM, c.hfovDeg, c.aspect);
      return { ...c, out: { x: r(p.x), y: r(p.y), zUp: r(p.zUp), rangeM: r(p.rangeM) } };
    }),
    stepDetector: { samples: stream, stepTimesMs: stepTimes },
  };
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  mkdirSync(dirname(VECTORS_PATH), { recursive: true });
  writeFileSync(VECTORS_PATH, JSON.stringify(buildVectors(), null, 1) + "\n");
  console.log(`wrote ${VECTORS_PATH}`);
}
